url: "https://jonghyeonbang.github.io"   # 사이트 기본 도메인
baseurl: "/JonghyeonBang"                # 리포지토리 이름을 그대로

# 사이트 기본 정보
title: "Jonghyeon Bang's Website"
description: "I try to make my own website"

# 원격 테마 선언
remote_theme: andreondra/jekyll-theme-simplex

# 필요한 플러그인
plugins:
  - jekyll-remote-theme

# 네비게이션 메뉴
navigation:
  - text: Home
    url: /
  - text: About
    url: /about/
  - text: Projects
    url: /projects/
  - text: Contact
    url: /contact/


# git add -A
# git commit -m "Save all current layout and style customizations"
# git push origin main